// shared/constants.js

/**
 * CLEARPATH SUPPLY CHAIN NODES (ROLES)
 * Humne roles ko logic-wise group kiya hai taaki management easy ho.
 */
const ROLES = {
    // TIER 1: ORIGIN & PRODUCTION
    FARMER: 'FARMER',
    PRODUCER: 'PRODUCER',
    RAW_MATERIAL_SUPPLIER: 'RAW_MATERIAL_SUPPLIER',
    MANUFACTURER: 'MANUFACTURER',

    // TIER 2: QUALITY & REGULATION (Trust Enforcers)
    QUALITY_INSPECTOR: 'QUALITY_INSPECTOR',
    LAB_TECHNICIAN: 'LAB_TECHNICIAN',
    CERTIFICATION_BODY: 'CERTIFICATION_BODY',
    HEALTH_OFFICER: 'HEALTH_OFFICER',
    REGULATOR: 'REGULATOR', // [cite: 47, 49]

    // TIER 3: LOGISTICS & STORAGE
    WAREHOUSE_MANAGER: 'WAREHOUSE_MANAGER', // [cite: 76, 82]
    COLD_STORAGE_OPERATOR: 'COLD_STORAGE_OPERATOR',
    LOGISTICS_COORDINATOR: 'LOGISTICS_COORDINATOR',
    TRANSPORTER_DRIVER: 'TRANSPORTER_DRIVER',
    CUSTOMS_OFFICER: 'CUSTOMS_OFFICER',

    // TIER 4: SALES & DISTRIBUTION
    DISTRIBUTOR: 'DISTRIBUTOR', // [cite: 10, 54]
    WHOLESALER: 'WHOLESALER',
    RETAILER: 'RETAILER',
    E_COMMERCE_HUB: 'E_COMMERCE_HUB'
};

/**
 * PRODUCT LIFECYCLE EVENTS
 * Har product ki journey in events ke through record hogi.
 */
const EVENT_TYPES = {
    // Production Phase
    HARVESTED: 'HARVESTED',
    SOURCED: 'SOURCED',
    MANUFACTURED: 'MANUFACTURED', // [cite: 59]
    BATCH_CREATED: 'BATCH_CREATED',

    // Quality Phase
    QUALITY_CHECK_STARTED: 'QUALITY_CHECK_STARTED',
    QUALITY_CHECK_PASSED: 'QUALITY_CHECK_PASSED',
    QUALITY_CHECK_FAILED: 'QUALITY_CHECK_FAILED',
    CERTIFICATION_ISSUED: 'CERTIFICATION_ISSUED',

    // Logistics Phase
    PACKAGED: 'PACKAGED',
    SHIPPED: 'SHIPPED', // [cite: 121, 240]
    IN_TRANSIT: 'IN_TRANSIT',
    RECEIVED_AT_FACILITY: 'RECEIVED_AT_FACILITY',
    DISPATCHED: 'DISPATCHED',

    // Final Phase
    STOCKED_AT_RETAIL: 'STOCKED_AT_RETAIL',
    DELIVERED: 'DELIVERED',
    EXPIRED: 'EXPIRED',
    RECALLED: 'RECALLED' // Emergency recalls ke liye
};

module.exports = { ROLES, EVENT_TYPES };